config/routes.rb
Rails.application.routes.draw do
  resources :airport_opening_times, only: [:new, :create]
  root to: "airport_opening_times#new"
end

app/controllers/airport_opening_times_controller.rb
class AirportOpeningTimesController < ApplicationController
  def new
  end

  def create
    notams_txt = params[:notams].read
    notams = NotamSelector.new(notams_txt).select
    @notams = notams.map { |notam| NotamParser.new(notam) }
    @notams.each { |notam| notam.parse! }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airport_opening_times/create.html.erb
<h4>Notam result</h4>
<table class="table">
  <tr>
    <th>Airport (ICAO code)</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thrusday</th>
    <th>Friday</th>
    <th>Saturday</th>
    <th>Sunday</th>
  </tr>
<% @notams.each do |notam| %>
  <tr>
    <td><%= notam.a_section %></td>
    <% notam.opening_times.each do |time| %>
      <td><%= time.gsub(" ", "<br />").html_safe %></td>
    <% end %>
  </tr>
<% end %>
</table>
<a class="btn btn-primary" href="/" role="button">Back</a>

app/views/airport_opening_times/new.html.erb
<h4>Upload notam's to parse</h4>
<%= form_tag airport_opening_times_path, multipart: true do %>
  <div class="form-group">
    <label for="Notams">Notams to Upload</label>
    <%= file_field_tag :notams %>
    <p class="help-block">Select text file with NOTAM's separate by empty line</p>
  </div>
  <%= submit_tag "Process", class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notam</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <h3 class="text-muted">Airport opening times</h3>
        </div>
        <div class="col-md-3">
          <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/London_Heathrow_tower_and_Virgin_B747_%285048342074%29_%282%29.jpg/220px-London_Heathrow_tower_and_Virgin_B747_%285048342074%29_%282%29.jpg" />
        </div>
      </div>
      <%= yield %>
    </div>

  </body>
</html>